In [1]:
%pip install pandas

Requirement already satisfied: pandas in C:\Users\Suriy\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.1.0)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Suriy\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.9.0 in C:\Users\Suriy\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Suriy\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in C:\Users\Suriy\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.9.0->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("orders.csv")

In [7]:
df.columns

Index(['OrderID', 'CustomerName', 'Product', 'Category', 'Quantity', 'Price',
       'OrderDate', 'Shipped', 'Country'],
      dtype='str')

In [9]:
df.head(10)

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan

In [15]:
df.iloc[8]

OrderID                1009
CustomerName    Maria Rossi
Product                 Pen
Category         Stationery
Quantity                 10
Price                   1.5
OrderDate        2024-06-10
Shipped                 Yes
Country               Italy
Name: 8, dtype: object

In [17]:
df[df['Price'] > 100]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,India
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,China
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal

In [25]:
df[(df['Category'] =='Furniture') & (df['Shipped'] == 'Yes')]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,Germany
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine